// This file will be auto-generated by `supabase gen types typescript`
// For now, we define a minimal Database type to avoid build errors.
// Run `npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/db/types.ts`
// after connecting to your Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          email: string;
          phone: string | null;
          gstin: string | null;
          pan: string | null;
          address: Json | null;
          subscription_plan: "starter" | "professional" | "enterprise";
          subscription_status: "trialing" | "active" | "past_due" | "cancelled" | "paused";
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          trial_ends_at: string | null;
          max_branches: number;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          email: string;
          phone?: string | null;
          gstin?: string | null;
          pan?: string | null;
          address?: Json | null;
          subscription_plan?: "starter" | "professional" | "enterprise";
          subscription_status?: "trialing" | "active" | "past_due" | "cancelled" | "paused";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          max_branches?: number;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo_url?: string | null;
          email?: string;
          phone?: string | null;
          gstin?: string | null;
          pan?: string | null;
          address?: Json | null;
          subscription_plan?: "starter" | "professional" | "enterprise";
          subscription_status?: "trialing" | "active" | "past_due" | "cancelled" | "paused";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          max_branches?: number;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      branches: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          code: string;
          address: Json | null;
          phone: string | null;
          email: string | null;
          gstin: string | null;
          timezone: string;
          currency: string;
          is_active: boolean;
          settings: Json;
          operating_hours: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          code: string;
          address?: Json | null;
          phone?: string | null;
          email?: string | null;
          gstin?: string | null;
          timezone?: string;
          currency?: string;
          is_active?: boolean;
          settings?: Json;
          operating_hours?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          code?: string;
          address?: Json | null;
          phone?: string | null;
          email?: string | null;
          gstin?: string | null;
          timezone?: string;
          currency?: string;
          is_active?: boolean;
          settings?: Json;
          operating_hours?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tenant_users: {
        Row: {
          id: string;
          user_id: string;
          tenant_id: string;
          branch_id: string | null;
          role: "super_admin" | "tenant_owner" | "branch_manager" | "cashier" | "waiter" | "kitchen_staff";
          display_name: string;
          avatar_url: string | null;
          pin_code: string | null;
          phone: string | null;
          is_active: boolean;
          permissions: Json;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tenant_id: string;
          branch_id?: string | null;
          role?: "super_admin" | "tenant_owner" | "branch_manager" | "cashier" | "waiter" | "kitchen_staff";
          display_name: string;
          avatar_url?: string | null;
          pin_code?: string | null;
          phone?: string | null;
          is_active?: boolean;
          permissions?: Json;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tenant_id?: string;
          branch_id?: string | null;
          role?: "super_admin" | "tenant_owner" | "branch_manager" | "cashier" | "waiter" | "kitchen_staff";
          display_name?: string;
          avatar_url?: string | null;
          pin_code?: string | null;
          phone?: string | null;
          is_active?: boolean;
          permissions?: Json;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      menu_categories: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          name_local: string | null;
          slug: string;
          image_url: string | null;
          sort_order: number;
          is_active: boolean;
          parent_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          name_local?: string | null;
          slug: string;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          parent_id?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          name_local?: string | null;
          slug?: string;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          parent_id?: string | null;
        };
      };
      menu_items: {
        Row: {
          id: string;
          tenant_id: string;
          category_id: string;
          name: string;
          name_local: string | null;
          description: string | null;
          image_url: string | null;
          base_price: number;
          hsn_sac_code: string | null;
          gst_rate: number;
          is_veg: boolean;
          is_active: boolean;
          is_available: boolean;
          sort_order: number;
          preparation_time: number;
          tags: string[] | null;
          nutritional_info: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          category_id: string;
          name: string;
          name_local?: string | null;
          description?: string | null;
          image_url?: string | null;
          base_price: number;
          hsn_sac_code?: string | null;
          gst_rate?: number;
          is_veg?: boolean;
          is_active?: boolean;
          is_available?: boolean;
          sort_order?: number;
          preparation_time?: number;
          tags?: string[] | null;
          nutritional_info?: Json | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          category_id?: string;
          name?: string;
          name_local?: string | null;
          description?: string | null;
          image_url?: string | null;
          base_price?: number;
          hsn_sac_code?: string | null;
          gst_rate?: number;
          is_veg?: boolean;
          is_active?: boolean;
          is_available?: boolean;
          sort_order?: number;
          preparation_time?: number;
          tags?: string[] | null;
          nutritional_info?: Json | null;
        };
      };
      orders: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          order_number: string;
          order_type: "dine_in" | "takeaway" | "delivery" | "kiosk" | "aggregator";
          status: "draft" | "confirmed" | "preparing" | "ready" | "served" | "completed" | "cancelled";
          table_id: string | null;
          customer_id: string | null;
          waiter_id: string | null;
          subtotal: number;
          discount_amount: number;
          discount_id: string | null;
          tax_amount: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          service_charge: number;
          total: number;
          aggregator_platform: "zomato" | "swiggy" | "uber_eats" | null;
          aggregator_order_id: string | null;
          delivery_address: Json | null;
          delivery_notes: string | null;
          notes: string | null;
          is_paid: boolean;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          order_number: string;
          order_type: "dine_in" | "takeaway" | "delivery" | "kiosk" | "aggregator";
          status?: "draft" | "confirmed" | "preparing" | "ready" | "served" | "completed" | "cancelled";
          table_id?: string | null;
          customer_id?: string | null;
          waiter_id?: string | null;
          subtotal?: number;
          discount_amount?: number;
          discount_id?: string | null;
          tax_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          service_charge?: number;
          total?: number;
          aggregator_platform?: "zomato" | "swiggy" | "uber_eats" | null;
          aggregator_order_id?: string | null;
          delivery_address?: Json | null;
          delivery_notes?: string | null;
          notes?: string | null;
          is_paid?: boolean;
          paid_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          order_number?: string;
          order_type?: "dine_in" | "takeaway" | "delivery" | "kiosk" | "aggregator";
          status?: "draft" | "confirmed" | "preparing" | "ready" | "served" | "completed" | "cancelled";
          table_id?: string | null;
          customer_id?: string | null;
          waiter_id?: string | null;
          subtotal?: number;
          discount_amount?: number;
          discount_id?: string | null;
          tax_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          service_charge?: number;
          total?: number;
          aggregator_platform?: "zomato" | "swiggy" | "uber_eats" | null;
          aggregator_order_id?: string | null;
          delivery_address?: Json | null;
          delivery_notes?: string | null;
          notes?: string | null;
          is_paid?: boolean;
          paid_at?: string | null;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          tenant_id: string;
          menu_item_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          notes: string | null;
          modifiers: Json;
          is_cancelled: boolean;
          cancelled_reason: string | null;
          kot_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          tenant_id: string;
          menu_item_id: string;
          quantity?: number;
          unit_price: number;
          total_price: number;
          notes?: string | null;
          modifiers?: Json;
          is_cancelled?: boolean;
          cancelled_reason?: string | null;
          kot_id?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          tenant_id?: string;
          menu_item_id?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          notes?: string | null;
          modifiers?: Json;
          is_cancelled?: boolean;
          cancelled_reason?: string | null;
          kot_id?: string | null;
        };
      };
      kots: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          order_id: string;
          kot_number: string;
          status: "pending" | "in_progress" | "ready" | "served" | "cancelled";
          station: string;
          printed_at: string | null;
          accepted_at: string | null;
          ready_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          order_id: string;
          kot_number: string;
          status?: "pending" | "in_progress" | "ready" | "served" | "cancelled";
          station?: string;
          printed_at?: string | null;
          accepted_at?: string | null;
          ready_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          order_id?: string;
          kot_number?: string;
          status?: "pending" | "in_progress" | "ready" | "served" | "cancelled";
          station?: string;
          printed_at?: string | null;
          accepted_at?: string | null;
          ready_at?: string | null;
        };
      };
      payments: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          order_id: string;
          method: "cash" | "card" | "upi" | "wallet" | "split" | "online";
          status: "pending" | "completed" | "failed" | "refunded" | "partial";
          amount: number;
          tip_amount: number;
          gateway: string | null;
          gateway_order_id: string | null;
          gateway_payment_id: string | null;
          gateway_signature: string | null;
          gateway_response: Json | null;
          is_split: boolean;
          split_index: number | null;
          refund_amount: number | null;
          refund_reason: string | null;
          refunded_at: string | null;
          is_offline: boolean;
          synced_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          order_id: string;
          method: "cash" | "card" | "upi" | "wallet" | "split" | "online";
          status?: "pending" | "completed" | "failed" | "refunded" | "partial";
          amount: number;
          tip_amount?: number;
          gateway?: string | null;
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          gateway_signature?: string | null;
          gateway_response?: Json | null;
          is_split?: boolean;
          split_index?: number | null;
          refund_amount?: number | null;
          refund_reason?: string | null;
          refunded_at?: string | null;
          is_offline?: boolean;
          synced_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          order_id?: string;
          method?: "cash" | "card" | "upi" | "wallet" | "split" | "online";
          status?: "pending" | "completed" | "failed" | "refunded" | "partial";
          amount?: number;
          tip_amount?: number;
          gateway?: string | null;
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          gateway_signature?: string | null;
          gateway_response?: Json | null;
          is_split?: boolean;
          split_index?: number | null;
          refund_amount?: number | null;
          refund_reason?: string | null;
          refunded_at?: string | null;
          is_offline?: boolean;
          synced_at?: string | null;
          created_by?: string | null;
        };
      };
      customers: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          phone: string | null;
          email: string | null;
          date_of_birth: string | null;
          anniversary: string | null;
          address: Json | null;
          preferences: Json;
          tags: string[] | null;
          total_orders: number;
          total_spent: number;
          loyalty_points: number;
          loyalty_tier: string;
          last_visit_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          anniversary?: string | null;
          address?: Json | null;
          preferences?: Json;
          tags?: string[] | null;
          total_orders?: number;
          total_spent?: number;
          loyalty_points?: number;
          loyalty_tier?: string;
          last_visit_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          anniversary?: string | null;
          address?: Json | null;
          preferences?: Json;
          tags?: string[] | null;
          total_orders?: number;
          total_spent?: number;
          loyalty_points?: number;
          loyalty_tier?: string;
          last_visit_at?: string | null;
        };
      };
      restaurant_tables: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          table_number: string;
          capacity: number;
          status: "available" | "occupied" | "reserved" | "cleaning" | "blocked";
          floor: string;
          position_x: number;
          position_y: number;
          shape: string;
          is_active: boolean;
          current_order_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          table_number: string;
          capacity?: number;
          status?: "available" | "occupied" | "reserved" | "cleaning" | "blocked";
          floor?: string;
          position_x?: number;
          position_y?: number;
          shape?: string;
          is_active?: boolean;
          current_order_id?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          table_number?: string;
          capacity?: number;
          status?: "available" | "occupied" | "reserved" | "cleaning" | "blocked";
          floor?: string;
          position_x?: number;
          position_y?: number;
          shape?: string;
          is_active?: boolean;
          current_order_id?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_order_number: {
        Args: { p_tenant_id: string; p_branch_id: string };
        Returns: string;
      };
    };
    Enums: {
      user_role: "super_admin" | "tenant_owner" | "branch_manager" | "cashier" | "waiter" | "kitchen_staff";
      order_type: "dine_in" | "takeaway" | "delivery" | "kiosk" | "aggregator";
      order_status: "draft" | "confirmed" | "preparing" | "ready" | "served" | "completed" | "cancelled";
      kot_status: "pending" | "in_progress" | "ready" | "served" | "cancelled";
      payment_method: "cash" | "card" | "upi" | "wallet" | "split" | "online";
      payment_status: "pending" | "completed" | "failed" | "refunded" | "partial";
      table_status: "available" | "occupied" | "reserved" | "cleaning" | "blocked";
      reservation_status: "pending" | "confirmed" | "seated" | "completed" | "cancelled" | "no_show";
      stock_movement_type: "purchase" | "sale" | "waste" | "transfer" | "adjustment";
      po_status: "draft" | "sent" | "partial" | "received" | "cancelled";
      discount_type: "percentage" | "fixed" | "bogo" | "happy_hour";
      subscription_plan: "starter" | "professional" | "enterprise";
      subscription_status: "trialing" | "active" | "past_due" | "cancelled" | "paused";
      aggregator_platform: "zomato" | "swiggy" | "uber_eats";
      shift_status: "scheduled" | "clocked_in" | "clocked_out" | "absent";
    };
  };
};

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
